### ISSUE TITLE
Unix issues

### ISSUE THREAD

**Issue by ne3x7** [ALSETLab/RaPId#55]
Hello. Thank you for the awesome software you developed.

However, I have several issues installing and using it, that I would like to resolve with your preferable assistance. I am trying to install RaPId on a unix machine using last version in Releases section, Matlab 2014b and FMI Toolbox 2.6.4.

First of all, RaPId has dependency on Matlab up to 2014b and also Modelon FMI Toolkit, which is (according to Modelon) incompatible with Matlab 2014b.

Second, RaPId messes paths on unix. I was able to resolve it during the installation process by simply modifying the script. However, the problem seems to go very much under the hood to the extent that I can not fix it. It shows up when I try to run any example. It produces a warning like "FMI Toolbox was not able to load FMU into Simulink, because FMU was not found at relative path", which shows a corrupted path. I am also not able to open FMUme block in Simulink.

I would be very grateful for assistance.

**Comment by lvanfretti** [comment]
Hi @ne3x7 

The current release works fine in Matlab 2016b, 2017a, 2017b, and 2018a in my testing with the latest FMI Toolbox from Modelon (v2.6.?). 

All tests have been done under Windows 10 (using Virtual Machines).
I have not tested anything recently under any other environments.

We have not tried installing RaPId on UNIX, only GNU/Linux distributions and Windows.

Could you tell us more details on what kind of OS you are working with, is it really UNIX or some flavor of GNU/Linux?

Also, can you please install the latest versions of Matlab/Simulink supported by the FMI Toolbox?

I can't promise we will resolve the issues, but I will ask my students to look into this using Ubuntu v16.?.? LTS, which is what we have in our student computers and our own servers. We can also test in a version of Red Hat, but don't recall which one we have in that server.

In the mean time, I recommend you install virtual box, and then load a virtual machine in your UNIX box with Windows 10 and associated dependencies.

@GiuseppeLaera can you talk with Meaghan to look into testing under Ubuntu 16? I will also mention it to her when she starts working on fixing the GUI.

**Comment by mpodlaski** [comment]
Hi @ne3x7,

I am able to run RaPId on Ubuntu using MATLAB 2018b. Have you tried using a newer version of MATLAB? I also have to run the setup_rapid file every time I open MATLAB in Ubuntu v16.1.2, so double check with that.

From there, the issue with not being able to open the FMUme block in Simulink is most likely an issue with the FMI Toolbox itself. I've had that issue when using MATLAB2015a. Can you run the examples in the FMI Toolbox folder?

**Comment by ne3x7** [comment]
Hi @lvanfretti! Thanks for your prompt answer.

I am actually running Mac OS, but it should not be much different from Ubuntu. I tried upgrading Matlab to R2018b and it seems to resolve the issue with paths. However I am still unable to run the example because of the error produced by FMI Toolbox. Also I have a warning about Statistics Toolbox, because it seems to be renamed to Machine Learning and Statistics Toolbox, but it's probably OK.

@mpodlaski, thank you too. The issue seems to be indeed connected with FMI Toolbox. The examples provided in the FMI Toolbox folder do not work for me neither from Matlab, neither from Simulink. Can you please advise me what to do, should I contact Modelon support?

**Comment by mpodlaski** [comment]
Hi @ne3x7,

Double check that the FMI Toolbox is installed correct by following the troubleshooting from the manual. If there's no luck there, your best bet is to contact Modelon support.
